//
// Created by Kok on 4/9/26.
//

#ifndef STM32_DIGITAL_POTENTIOMETER_V2_LOGGING_H
#define STM32_DIGITAL_POTENTIOMETER_V2_LOGGING_H

void LOGGING_Init();

#endif //STM32_DIGITAL_POTENTIOMETER_V2_LOGGING_H